### ISSUE TITLE
String times get interpreted in a wrong way 

### ISSUE THREAD

**Issue by aboueleyes** [adamchainz/time-machine#348]
### Python Version

3.10

### Description

```
class TempTest(TestCase):
    @travel(datetime.datetime(2020, 6, 1, 0, 0, 0))
    def test_time(self):
        print(timezone.now())
        self.assertEqual(datetime.date(2020, 6, 1), timezone.now().date())
        self.assertEqual(timezone.now().date(), datetime.date(2020, 6, 1))

    @travel("2020-06-01")
    def test_time2(self):
        print(timezone.now())
        self.assertEqual(datetime.date(2020, 6, 1), timezone.now().date())
        self.assertEqual(timezone.now().date(), datetime.date(2020, 6, 1))
```
```
2020-06-01 00:00:00+00:00
.2020-05-31 22:00:00+00:00
F
======================================================================
FAIL: test_time2 (shahry.core.tests.test_utils.TempTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/time_machine/__init__.py", line 336, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/shahry/core/tests/test_utils.py", line 783, in test_time2
    self.assertEqual(datetime.date(2020, 6, 1), timezone.now().date())
AssertionError: datetime.date(2020, 6, 1) != datetime.date(2020, 5, 31)
```
for some reason when using"2020-06-01" the time is getting wrong

**Comment by aboueleyes** [comment]
yes, it would be helpful 
I guess freezegun have it treated it that way, so it will also make it easier to migrate from freezegun

**Comment by adamchainz** [comment]
No, freezegun uses dateutil, so this would be an incompatibility.

**Comment by Siburg** [comment]
See #306 . I actually prefer the interpretation of a string to be in the timezone from my settings.
